name: yt_feed Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-test:
    name: python test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check for .env file
        run: |
          if [ -f ".env" ]; then
            echo "Error: .env file is present!"
            exit 1
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev


      - name: install-precommit
        run: uv tool install pre-commit

      - name: Run Jinja2 script to update README
        run: |
          uv run python tools/update_readme.py

      - name: run-precommit
        run: pre-commit run --show-diff-on-failure --color=always -a

      - name: Commit and push if on PR
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add README.md
          timestamp=$(date -u)
          git commit -m "$GITHUB_SHA Triggered a README.md update ${timestamp}" || exit 0
          git push
        if: github.event_name == 'pull_request'

      - name: fail if readme changed and we aren't on PR
        uses: nickcharlton/diff-check@main
        if: github.event_name != 'pull_request'

      - name: Test with pytest
        run: |
          uv run python -m pytest
